// Generated by scripts/generate-web-dashboard.mjs. Do not edit manually.

export const dashboardData = {
  "schemaVersion": 2,
  "route": "/dashboard",
  "title": "Private AOS Mirror Max",
  "updated": "2026-07-09",
  "generatedAt": "2026-07-08T16:02:24",
  "dataDate": "2026-07-08",
  "summary": "A Cloudflare Access-gated CJ Cinco mirror of the local Aligned OS command dashboard, exported through a redacted snapshot layer.",
  "access": {
    "label": "Cloudflare Access",
    "value": "Existing gate",
    "detail": "Static dashboard content is protected by the existing CJ Cinco Access application before the route loads."
  },
  "privacy": {
    "status": "passed",
    "label": "Redacted export",
    "detail": "Only whitelisted dashboard summaries, counts, status labels, and approved Wealth totals are rendered.",
    "checks": [
      "No contact-pattern strings",
      "No local source paths",
      "No raw communication text",
      "No account-like identifiers",
      "No row-level private evidence"
    ]
  },
  "freshness": {
    "status": "stale",
    "label": "5 freshness item(s)",
    "checkedAt": "2026-07-08T16:02:24-04:00",
    "detail": "Captain projection needs a sync pass before treating every current surface as fresh."
  },
  "nav": [
    {
      "key": "overview",
      "title": "Overview"
    },
    {
      "key": "cj-cinco",
      "title": "CJ Cinco"
    },
    {
      "key": "areas",
      "title": "Area State"
    },
    {
      "key": "wealth",
      "title": "Wealth"
    },
    {
      "key": "vtc",
      "title": "VTC"
    },
    {
      "key": "content",
      "title": "Content / Social"
    },
    {
      "key": "coaching",
      "title": "Coaching"
    },
    {
      "key": "system",
      "title": "System"
    }
  ],
  "metrics": [
    {
      "label": "Access",
      "value": "Gated",
      "detail": "Cloudflare Access remains the authentication boundary.",
      "tone": "green"
    },
    {
      "label": "Freshness",
      "value": "5 sync",
      "detail": "Projection freshness from the local AOS dashboard.",
      "tone": "watch"
    },
    {
      "label": "Pace",
      "value": "41 behind",
      "detail": "One Thing pace from the generated local dashboard summary.",
      "tone": "alert"
    },
    {
      "label": "Areas",
      "value": "8",
      "detail": "Core and support lanes mirrored as redacted status cards.",
      "tone": "cyan"
    },
    {
      "label": "Open Queues",
      "value": "6",
      "detail": "Queue counts only; item names and raw files are not exported.",
      "tone": "watch"
    },
    {
      "label": "Net Worth",
      "value": "$123,495",
      "detail": "Latest approved Wealth dashboard row: 2026-07.",
      "tone": "gold"
    },
    {
      "label": "VTC Target",
      "value": "$1,923+",
      "detail": "Current revenue proof target, with record-level details withheld.",
      "tone": "green"
    },
    {
      "label": "Social",
      "value": "9 scheduled",
      "detail": "Approval-gated content queue counts only.",
      "tone": "cyan"
    }
  ],
  "captain": {
    "status": "yellow",
    "signal": "not complete",
    "oneThing": {
      "owner": "Captain",
      "current": "Work the active VTC revenue board from Linear, especially the active VTC handoff and current VTC follow-up floor in project Vero Tech Care.",
      "supports": "MAP 1-Year Goal #6 and first-cycle 1-Month Goals #6-7 for the VTC revenue push and local-trust proof.",
      "doneWhen": "the active VTC Linear issue gets a concrete next proof: booked/collected work, resolved service relationships blocker, sent/approved follow-up, or updated AOS service pr..."
    },
    "readout": {
      "posture": "Loaded but workable.",
      "movement": "VTC remains the live revenue driver; Health has Apple Health/device export infrastructure and a weekly shortcut/processor path; Wealth ledger/dashboard truth is fresher than the p...",
      "exposure": "Medium-high until active VTC service relationships/follow-up loops, benefit application review-marker cleanup, the first Health weekly export proof, and the next Home room reset a..."
    }
  },
  "areas": [
    {
      "slug": "health",
      "name": "Health",
      "tier": "Core",
      "status": "yellow",
      "missionLink": "primary track",
      "scorecard": {
        "grade": "B-",
        "momentum": "Medium",
        "risk": "Medium",
        "upgrade": "keep the 10 / 10 / 10 baseline visible while proving the weekly export path and first-cycle training/mobility rhythm."
      },
      "oneThing": {
        "owner": "Health",
        "current": "Keep using the same-day Obsidian daily checklist as the 10 / 10 / 10 Health baseline proof while protecting post-hospitalization professional-care continuity and monitor...",
        "supports": "MAP Health / Mind 1-Year Goals #1-3: body composition, race readiness, and reading as mind-development proof.",
        "doneWhen": "today's Body, Mind, and Soul baseline checks are visible in the daily checklist, real training details are logged separately when they happen, and the first scheduled we..."
      },
      "supportGaps": [
        "Keep using the Obsidian daily checklist for the 10 / 10 / 10 baseline.",
        "Confirm professional-care continuity and follow-up questions with qualified professionals.",
        "Ask qualified professionals whether recent health-marker flags need follow-up."
      ],
      "queue": {
        "open": 0,
        "status": "clear"
      }
    },
    {
      "slug": "people",
      "name": "The People",
      "tier": "Core",
      "status": "yellow",
      "missionLink": "primary track",
      "scorecard": {
        "grade": "C+",
        "momentum": "Low to medium",
        "risk": "Medium",
        "upgrade": "use the new relationship move template in a real family relationship block and trim it if it feels too heavy."
      },
      "oneThing": {
        "owner": "The People",
        "current": "Keep People work focused on live Linear items and relationship repair practice; do not carry the private touchpoint.",
        "supports": "MAP 1-Year Goals #4-5 for marriage stability, family presence, relationship repair, homeschool rhythm, and kid-friendly family-business exposure.",
        "doneWhen": "the current People Linear item has a clear next proof, and private relationship context remains in AOS."
      },
      "supportGaps": [
        "Use source note in three real trigger moments this week, including the timeout script before escalation when possible.",
        "Use source note to return and choose one clean repair/teamwork line after regulation.",
        "Use source note as a behavior prompt only, especially for the next family relationship repair/teamwork block."
      ],
      "queue": {
        "open": 0,
        "status": "clear"
      }
    },
    {
      "slug": "home",
      "name": "Home",
      "tier": "Core",
      "status": "yellow",
      "missionLink": "primary track",
      "scorecard": {
        "grade": "C",
        "momentum": "Medium",
        "risk": "Medium",
        "upgrade": "complete the next non-gym room reset without letting Facebook sale follow-up, yard momentum, or loose clutter reclaim the protected gym zone."
      },
      "oneThing": {
        "owner": "Home",
        "current": "Start Studio Room by removing clutter, then work the futon, bed/frame, under-bed storage, and cord sequence.",
        "supports": "Whole-home room reset, household calm, daily living function, and protected home-gym training access.",
        "doneWhen": "studio clutter is cleared enough to work safely, futon removal/sale is handled or staged, bed/frame is usable, under-bed storage has a clear purpose, loose cords are con..."
      },
      "supportGaps": [
        "Start Studio Room with Remove clutter.",
        "Move or list/stage the studio futon before bed/frame setup.",
        "Set up the studio bed/frame, then establish under-bed storage and contain cords."
      ],
      "queue": {
        "open": 1,
        "status": "open"
      }
    },
    {
      "slug": "wealth",
      "name": "Wealth",
      "tier": "Core",
      "status": "yellow",
      "missionLink": "supporting front",
      "scorecard": {
        "grade": "B",
        "momentum": "Medium",
        "risk": "Medium.",
        "upgrade": "review the regenerated Wealth dashboard after the 2026-07-03 recent service correction, then keep S corp cleanup and benefit application work separated in Linear."
      },
      "oneThing": {
        "owner": "Wealth",
        "current": "Build the first S corp cleanup decision packet from the selected Gary Keller sequence.",
        "supports": "the tax/entity north star, clean Aligned Harmonics operating path, monthly books, tax reserve, CPA tax plan, and eventual first real estate acquisition model.",
        "doneWhen": "the packet identifies the evidence needed, names the S corp election/payroll/bookkeeping/tax-reserve questions, and gives CJ a clear CPA/professional-review ask or next..."
      },
      "supportGaps": [
        "Build the first S corp cleanup decision packet from the selected Gary Keller sequence.",
        "Choose one benefit application issue in Linear project Wealth to move next: professional-care/support follow-through or review-marker cleanup; for re...",
        "Review the regenerated Wealth dashboard after the approved 2026-06-23 comprehensive apply."
      ],
      "queue": {
        "open": 8,
        "status": "open"
      }
    },
    {
      "slug": "vtc",
      "name": "VTC",
      "tier": "Core",
      "status": "yellow",
      "missionLink": "primary track",
      "scorecard": {
        "grade": "B",
        "momentum": "High",
        "risk": "Medium",
        "upgrade": "tighten follow-up cadence, stale-record handling, and review/referral loop while keeping VTC the active revenue driver."
      },
      "oneThing": {
        "owner": "VTC",
        "current": "Work the active Linear VTC lanes in project Vero Tech Care, especially active VTC app handoff and the current follow-up floor. the active VTC handoff has now reached the...",
        "supports": "MAP 1-Year Goal #6 and first-cycle 1-Month Goals #6-7 for the VTC revenue push and VTC Community Cleanup local-trust proof.",
        "doneWhen": "a working VTC issue has concrete proof in the service proof: resolved blocker, sent/approved follow-up, booking/payment signal, or updated next date."
      },
      "supportGaps": [
        "Execute the current follow-up floor from Linear project Vero Tech Care, using the active child/issues there rather than any static issue list in this...",
        "Watch for active app handoff acceptance and record the proof locally.",
        "Confirm VTC business contact aliases only inside local source systems."
      ],
      "queue": {
        "open": 3,
        "status": "open"
      }
    },
    {
      "slug": "aligned-harmonics",
      "name": "Aligned Harmonics",
      "tier": "Support",
      "status": "yellow",
      "missionLink": "support lane",
      "scorecard": {
        "grade": "B- after migration",
        "momentum": "Low to moderate by design",
        "risk": "Medium until migrated paths, skills, and validators are fully verified",
        "upgrade": "verify the new parent/sub-lane structure without activating support-business or creative expansion work."
      },
      "oneThing": {
        "owner": "Aligned Harmonics",
        "current": "Keep the Aligned Harmonics parent/sub-lane map source-clear after folding in CJ Cinco, Green Bodyworks, and Emerald Acres.",
        "supports": "MAP 1-Year Goal #9 and first-cycle 1-Month Goals #10-11 while keeping Social Raw approval-gated, CJ Cinco public-persona work findable, Green Bodyworks lightweight active, and Eme...",
        "doneWhen": "parent and sub-lane README/HANDOFF/assets/skills paths are verified, Social Raw remains approval-first, and no duplicate content tracker, local outbox, or support-business dashboa..."
      },
      "supportGaps": [
        "Verify the migrated paths and active skills after this restructuring.",
        "Drop local media, personal voice moments, and sensitive real-life context into the Social Raw intake lane.",
        "Review the first weekly Social Raw packet after the automation creates or updates its Linear review issue."
      ],
      "queue": {
        "open": 0,
        "status": "clear"
      }
    },
    {
      "slug": "cj-cinco",
      "name": "CJ Cinco",
      "tier": "Support",
      "status": "yellow",
      "missionLink": "support lane",
      "scorecard": {
        "grade": "C as newly created",
        "momentum": "New foundation",
        "risk": "Medium if social/persona work becomes a new content machine before source truth is clear",
        "upgrade": "finish first-line bio/headline and bio variants, confirm Linktree/link-in-bio order, preferred CTA, platform roles, and whether Green Bodyworks appears publicly under CJ Cinco."
      },
      "oneThing": {
        "owner": "CJ Cinco",
        "current": "Make CJ Cinco source-clear as the public persona and outward-facing brand lane under Aligned Harmonics.",
        "supports": "MAP 1-Year Goal #9 and first-cycle Aligned Harmonics album/concept work by separating public persona/brand communication from parent-company and music-production source truth.",
        "doneWhen": "CJ Cinco has a usable manager skeleton, website asset reference, public voice boundary, clear routing rule for social/persona work, and a durable roadmap for daily AI-assisted pos..."
      },
      "supportGaps": [
        "Finish the first-line bio/headline and short, medium, and long bio variants.",
        "Confirm Linktree order, labels, primary CTA, email path, whether cjcinco.com should become the first link, and whether Green Bodyworks appears.",
        "Confirm current public platforms/handles and platform roles."
      ],
      "queue": {
        "open": 0,
        "status": "clear"
      }
    },
    {
      "slug": "altered-states",
      "name": "Altered States",
      "tier": "Support",
      "status": "yellow",
      "missionLink": "support lane",
      "scorecard": {
        "grade": "B",
        "momentum": "Low by design",
        "risk": "Medium",
        "upgrade": "Keep parked support light and approval-gated."
      },
      "oneThing": {
        "owner": "Altered States",
        "current": "Process new support items in light mode only.",
        "supports": "MAP service-count proof path and owner-approved support boundaries.",
        "doneWhen": "The next item is routed, logged, or held for approval without activating a larger system."
      },
      "supportGaps": [
        "Keep broad expansion parked unless explicitly activated."
      ],
      "queue": {
        "open": 0,
        "status": "clear"
      }
    }
  ],
  "queues": [
    {
      "label": "Captain intake",
      "count": 3,
      "status": "open"
    },
    {
      "label": "Captain source artifacts",
      "count": 36,
      "status": "open"
    },
    {
      "label": "XO intake",
      "count": 0,
      "status": "clear"
    },
    {
      "label": "Health intake",
      "count": 0,
      "status": "clear"
    },
    {
      "label": "People intake",
      "count": 0,
      "status": "clear"
    },
    {
      "label": "Home intake",
      "count": 1,
      "status": "open"
    },
    {
      "label": "Wealth intake",
      "count": 8,
      "status": "open"
    },
    {
      "label": "VTC intake",
      "count": 3,
      "status": "open"
    },
    {
      "label": "Aligned Harmonics intake",
      "count": 0,
      "status": "clear"
    },
    {
      "label": "CJ Cinco intake",
      "count": 0,
      "status": "clear"
    },
    {
      "label": "Green Bodyworks intake",
      "count": 1,
      "status": "open"
    },
    {
      "label": "Emerald Acres intake",
      "count": 0,
      "status": "clear"
    },
    {
      "label": "Altered States intake",
      "count": 0,
      "status": "clear"
    }
  ],
  "wealth": {
    "month": "2026-07",
    "income": "$300",
    "expenses": "$0",
    "cashFlow": "$300",
    "assets": "$336,880",
    "liabilities": "$213,385",
    "netWorth": "$123,495",
    "dataStatus": "approved-ledger; approved-net-worth; approved-balance-sheet",
    "budget": {
      "incomeTarget": "$6,250",
      "outflowTarget": "$5,500",
      "targetCashFlow": "$750",
      "categories": [
        {
          "label": "Income",
          "value": "$6,250",
          "type": "Income"
        },
        {
          "label": "Home",
          "value": "$1,500",
          "type": "Outflow"
        },
        {
          "label": "Food",
          "value": "$450",
          "type": "Outflow"
        },
        {
          "label": "Transportation",
          "value": "$600",
          "type": "Outflow"
        },
        {
          "label": "Personal",
          "value": "$450",
          "type": "Outflow"
        },
        {
          "label": "Debt",
          "value": "$1,300",
          "type": "Outflow"
        },
        {
          "label": "Extras",
          "value": "$1,200",
          "type": "Outflow"
        }
      ]
    }
  },
  "vtc": {
    "status": "Needs Push",
    "target": "$1,923+",
    "deadline": "2026-07-31",
    "currentWeekCollected": "$0",
    "gapToTarget": "$1,923",
    "daysRemaining": 23,
    "counts": {
      "dueFollowups": 40,
      "warmOpportunities": 11,
      "partnerTouches": 18,
      "proofProgressPct": 0
    },
    "nextMove": "Move the highest-priority VTC service handoff or follow-up proof, then update the owning record locally."
  },
  "contentSocial": {
    "status": "Approval-gated",
    "activeTotal": 24,
    "scheduled": 9,
    "blocked": 4,
    "posted": 11,
    "attention": 4,
    "pendingPackets": 3,
    "weekRows": [
      {
        "label": "This week",
        "dateRange": "Jul 6 - Jul 12",
        "scheduled": 0,
        "posted": 2,
        "blocked": 1,
        "target": 3
      },
      {
        "label": "Week +1",
        "dateRange": "Jul 13 - Jul 19",
        "scheduled": 3,
        "posted": 0,
        "blocked": 0,
        "target": 3
      },
      {
        "label": "Week +2",
        "dateRange": "Jul 20 - Jul 26",
        "scheduled": 3,
        "posted": 0,
        "blocked": 0,
        "target": 3
      },
      {
        "label": "Week +3",
        "dateRange": "Jul 27 - Aug 2",
        "scheduled": 3,
        "posted": 0,
        "blocked": 0,
        "target": 3
      }
    ],
    "platforms": [
      {
        "label": "Nextdoor",
        "scheduled": 3,
        "blocked": 1,
        "posted": 4,
        "total": 8
      },
      {
        "label": "Facebook",
        "scheduled": 3,
        "blocked": 1,
        "posted": 4,
        "total": 8
      },
      {
        "label": "Google Business Profile",
        "scheduled": 3,
        "blocked": 2,
        "posted": 3,
        "total": 8
      }
    ]
  },
  "guardrails": {
    "accessPlan": [
      "Cloudflare Access protects the dashboard route and nested dashboard paths before static content loads.",
      "The dashboard stays on the existing CJ Cinco Cloudflare Pages project.",
      "The route remains absent from the public homepage, nav, footer, robots file, and sitemap.",
      "The Next.js app does not implement a separate login system."
    ],
    "sourceContract": [
      "Read only the bounded AOS generated dashboard snapshot, root command summaries, CJ Cinco lane summaries, and approved Wealth dashboard summary.",
      "Export AOS structure, goals, pressure, support gaps, coaching, queue counts, projection freshness, and summary metrics.",
      "Do not export raw communications, relationship records, local source paths, account details, credentials, private records, or raw evidence.",
      "Fail the build if deterministic leak checks find contact patterns, local paths, long account-like numbers, raw communication markers, or credential markers."
    ],
    "sourceLabels": [
      "AOS generated dashboard summary",
      "Master Command current readout",
      "CJ Cinco lane summaries",
      "Approved Wealth dashboard totals",
      "Approved Wealth budget totals"
    ]
  },
  "pages": [
    {
      "key": "overview",
      "title": "Overview",
      "kicker": "Command Mirror",
      "summary": "The private route mirrors the local command dashboard as status, pressure, proof, and queue summaries.",
      "sections": [
        {
          "title": "Captain One Thing",
          "kicker": "Current",
          "tone": "gold",
          "items": [
            {
              "label": "Current",
              "value": "Work the active VTC revenue board from Linear, especially the active VTC handoff and current VTC follow-up floor in project Vero Tech Care.",
              "detail": "MAP 1-Year Goal #6 and first-cycle 1-Month Goals #6-7 for the VTC revenue push and local-trust proof.",
              "tone": "gold"
            },
            {
              "label": "Done when",
              "value": "Proof visible",
              "detail": "the active VTC Linear issue gets a concrete next proof: booked/collected work, resolved service relationships blocker, sent/approved follow-up, or updated AOS service pr...",
              "tone": "green"
            }
          ]
        },
        {
          "title": "Operating Readout",
          "kicker": "Captain",
          "tone": "watch",
          "items": [
            {
              "label": "Posture",
              "value": "Loaded but workable.",
              "detail": "",
              "tone": "watch"
            },
            {
              "label": "Movement",
              "value": "Active",
              "detail": "VTC remains the live revenue driver; Health has Apple Health/device export infrastructure and a weekly shortcut/processor path; Wealth ledger/dashboard truth is fresher than the p...",
              "tone": "cyan"
            },
            {
              "label": "Exposure",
              "value": "Watch",
              "detail": "Medium-high until active VTC service relationships/follow-up loops, benefit application review-marker cleanup, the first Health weekly export proof, and the next Home room reset a...",
              "tone": "alert"
            }
          ]
        },
        {
          "title": "Maintain / Advance",
          "kicker": "Lens",
          "tone": "green",
          "items": [
            {
              "label": "Maintain",
              "value": "Protect stability",
              "detail": "Health, family, home function, finance visibility, and active service loops stay visible first.",
              "tone": "green"
            },
            {
              "label": "Advance",
              "value": "Move proof",
              "detail": "Revenue proof, public-persona clarity, Wealth decisions, and Aligned Harmonics source clarity advance only when maintenance stays realistic.",
              "tone": "cyan"
            }
          ]
        }
      ]
    },
    {
      "key": "cj-cinco",
      "title": "CJ Cinco",
      "kicker": "Public Persona",
      "summary": "CJ Cinco stays the outward-facing public identity while the operating system remains private and local.",
      "sections": [
        {
          "title": "Lane Status",
          "kicker": "CJ Cinco",
          "tone": "cyan",
          "items": [
            {
              "label": "Role",
              "value": "Public persona",
              "detail": "Music, healing, business, life, and communication-with-the-world context stay source-clear.",
              "tone": "cyan"
            },
            {
              "label": "Current focus",
              "value": "Bio and profile clarity",
              "detail": "Make CJ Cinco source-clear as the public persona and outward-facing brand lane under Aligned Harmonics.",
              "tone": "gold"
            },
            {
              "label": "Approval gate",
              "value": "Publishing held",
              "detail": "Posting, scheduling, public profile edits, and product activation still require explicit approval.",
              "tone": "alert"
            }
          ]
        },
        {
          "title": "Roadmap",
          "kicker": "Sequence",
          "tone": "gold",
          "items": [
            {
              "label": "Step 1",
              "value": "Finish the first-line bio/headline and short, medium, and long bio variants.",
              "detail": "",
              "tone": "gold"
            },
            {
              "label": "Step 2",
              "value": "Confirm Linktree order, labels, primary CTA, email path, whether cjcinco.com should become the first link, and whether Green Bodyworks appears.",
              "detail": "",
              "tone": "neutral"
            },
            {
              "label": "Step 3",
              "value": "Confirm current public platforms/handles and platform roles.",
              "detail": "",
              "tone": "neutral"
            },
            {
              "label": "Step 4",
              "value": "Refine cjcinco.com copy after the profile/link direction is approved.",
              "detail": "",
              "tone": "neutral"
            },
            {
              "label": "Step 5",
              "value": "Build the first 30-day content bank from Spirit - Truth - Health - Media - Motion before activating any daily posting automation.",
              "detail": "",
              "tone": "neutral"
            }
          ]
        }
      ]
    },
    {
      "key": "areas",
      "title": "Area State",
      "kicker": "AOS Structure",
      "summary": "Core and support lanes are shown as compact redacted cards with status, grade, risk, and next proof.",
      "sections": [
        {
          "title": "Core Lanes",
          "kicker": "Health / People / Home / Wealth / VTC",
          "tone": "watch",
          "items": [
            {
              "label": "Health",
              "value": "B- - Yellow",
              "detail": "keep the 10 / 10 / 10 baseline visible while proving the weekly export path and first-cycle training/mobility rhythm.",
              "tone": "watch"
            },
            {
              "label": "The People",
              "value": "C+ - Yellow",
              "detail": "use the new relationship move template in a real family relationship block and trim it if it feels too heavy.",
              "tone": "watch"
            },
            {
              "label": "Home",
              "value": "C - Yellow",
              "detail": "complete the next non-gym room reset without letting Facebook sale follow-up, yard momentum, or loose clutter reclaim the protected gym zone.",
              "tone": "watch"
            },
            {
              "label": "Wealth",
              "value": "B - Yellow",
              "detail": "review the regenerated Wealth dashboard after the 2026-07-03 recent service correction, then keep S corp cleanup and benefit application work separated in Linear.",
              "tone": "watch"
            },
            {
              "label": "VTC",
              "value": "B - Yellow",
              "detail": "tighten follow-up cadence, stale-record handling, and review/referral loop while keeping VTC the active revenue driver.",
              "tone": "watch"
            }
          ]
        },
        {
          "title": "Support Lanes",
          "kicker": "Aligned Harmonics / CJ Cinco / Altered States",
          "tone": "cyan",
          "items": [
            {
              "label": "Aligned Harmonics",
              "value": "B- after migration - Yellow",
              "detail": "verify the new parent/sub-lane structure without activating support-business or creative expansion work.",
              "tone": "cyan"
            },
            {
              "label": "CJ Cinco",
              "value": "C as newly created - Yellow",
              "detail": "finish first-line bio/headline and bio variants, confirm Linktree/link-in-bio order, preferred CTA, platform roles, and whether Green Bodyworks appears publicly under CJ Cinco.",
              "tone": "cyan"
            },
            {
              "label": "Altered States",
              "value": "B - Yellow",
              "detail": "Keep parked support light and approval-gated.",
              "tone": "cyan"
            }
          ]
        }
      ]
    },
    {
      "key": "wealth",
      "title": "Wealth",
      "kicker": "Approved Totals",
      "summary": "Only summary Wealth metrics and approved budget totals are exported.",
      "sections": [
        {
          "title": "Latest Month",
          "kicker": "2026-07",
          "tone": "gold",
          "items": [
            {
              "label": "Income",
              "value": "$300",
              "detail": "Approved dashboard summary.",
              "tone": "green"
            },
            {
              "label": "Expenses",
              "value": "$0",
              "detail": "Approved dashboard summary.",
              "tone": "watch"
            },
            {
              "label": "Cash Flow",
              "value": "$300",
              "detail": "Approved dashboard summary.",
              "tone": "green"
            },
            {
              "label": "Net Worth",
              "value": "$123,495",
              "detail": "approved-ledger; approved-net-worth; approved-balance-sheet",
              "tone": "gold"
            }
          ]
        },
        {
          "title": "Budget Targets",
          "kicker": "Monthly",
          "tone": "cyan",
          "items": [
            {
              "label": "Income target",
              "value": "$6,250",
              "detail": "",
              "tone": "green"
            },
            {
              "label": "Outflow target",
              "value": "$5,500",
              "detail": "",
              "tone": "watch"
            },
            {
              "label": "Target cash flow",
              "value": "$750",
              "detail": "",
              "tone": "cyan"
            }
          ]
        }
      ]
    },
    {
      "key": "vtc",
      "title": "VTC",
      "kicker": "Revenue Pressure",
      "summary": "VTC appears as runway, follow-up pressure, and proof progress without row-level service records.",
      "sections": [
        {
          "title": "Runway",
          "kicker": "Target",
          "tone": "watch",
          "items": [
            {
              "label": "Status",
              "value": "Needs Push",
              "detail": "Deadline: 2026-07-31.",
              "tone": "watch"
            },
            {
              "label": "Target",
              "value": "$1,923+",
              "detail": "Gap: $1,923.",
              "tone": "gold"
            },
            {
              "label": "Current week",
              "value": "$0",
              "detail": "23 day(s) remaining in the push window.",
              "tone": "cyan"
            }
          ]
        },
        {
          "title": "Follow-Up Pressure",
          "kicker": "Counts",
          "tone": "alert",
          "items": [
            {
              "label": "Due follow-ups",
              "value": "40",
              "detail": "Count only; no row details exported.",
              "tone": "alert"
            },
            {
              "label": "Warm opportunities",
              "value": "11",
              "detail": "Count only; no names or contact data exported.",
              "tone": "watch"
            },
            {
              "label": "Partner touches",
              "value": "18",
              "detail": "Count only.",
              "tone": "cyan"
            },
            {
              "label": "Next move",
              "value": "Service proof",
              "detail": "Move the highest-priority VTC service handoff or follow-up proof, then update the owning record locally.",
              "tone": "green"
            }
          ]
        }
      ]
    },
    {
      "key": "content",
      "title": "Content / Social",
      "kicker": "Approval-Gated",
      "summary": "The content page shows queue health and platform counts only; no post copy is exported.",
      "sections": [
        {
          "title": "Queue Health",
          "kicker": "Social Raw",
          "tone": "cyan",
          "items": [
            {
              "label": "Active rows",
              "value": "24",
              "detail": "Approved/scheduled/social rows counted without copy text.",
              "tone": "cyan"
            },
            {
              "label": "Scheduled",
              "value": "9",
              "detail": "",
              "tone": "green"
            },
            {
              "label": "Blocked",
              "value": "4",
              "detail": "Requires review or platform proof before movement.",
              "tone": "alert"
            },
            {
              "label": "Pending packets",
              "value": "3",
              "detail": "Draft packet counts only.",
              "tone": "watch"
            }
          ]
        },
        {
          "title": "Platform Counts",
          "kicker": "Rows",
          "tone": "green",
          "items": [
            {
              "label": "Nextdoor",
              "value": "3 scheduled",
              "detail": "4 posted, 1 blocked, 8 total.",
              "tone": "watch"
            },
            {
              "label": "Facebook",
              "value": "3 scheduled",
              "detail": "4 posted, 1 blocked, 8 total.",
              "tone": "watch"
            },
            {
              "label": "Google Business Profile",
              "value": "3 scheduled",
              "detail": "3 posted, 2 blocked, 8 total.",
              "tone": "watch"
            }
          ]
        }
      ]
    },
    {
      "key": "coaching",
      "title": "Coaching",
      "kicker": "Signals",
      "summary": "Coaching strips convert AOS pressure into action language without exposing raw evidence.",
      "sections": [
        {
          "title": "Leverage Now",
          "kicker": "Move Order",
          "tone": "gold",
          "items": [
            {
              "label": "1. Captain",
              "value": "Work the active VTC revenue board from Linear, especially the active VTC handoff and current VTC follow-up fl...",
              "detail": "the active VTC Linear issue gets a concrete next proof: booked/collected work, resolved service relationships blocker, sent/approved follow-up, or up...",
              "tone": "gold"
            },
            {
              "label": "2. VTC",
              "value": "Work the active Linear VTC lanes in project Vero Tech Care, especially active VTC app handoff and th...",
              "detail": "a working VTC issue has concrete proof in the service proof: resolved blocker, sent/approved follow-up, booking/payment signal, or updated next date.",
              "tone": "neutral"
            },
            {
              "label": "3. VTC",
              "value": "Execute the current follow-up floor from Linear project Vero Tech Care, using the active child/issues there...",
              "detail": "Move is started, delegated, or logged in the owning area.",
              "tone": "neutral"
            },
            {
              "label": "4. Health",
              "value": "Keep using the same-day Obsidian daily checklist as the 10 / 10 / 10 Health baseline proof while protecting p...",
              "detail": "today's Body, Mind, and Soul baseline checks are visible in the daily checklist, real training details are logged separately when they happen, and th...",
              "tone": "neutral"
            },
            {
              "label": "5. Home",
              "value": "Start Studio Room by removing clutter, then work the futon, bed/frame, under-bed storage, and cord sequence.",
              "detail": "studio clutter is cleared enough to work safely, futon removal/sale is handled or staged, bed/frame is usable, under-bed storage has a clear purpose,...",
              "tone": "neutral"
            }
          ]
        },
        {
          "title": "Support Gaps",
          "kicker": "Area Needs",
          "tone": "watch",
          "items": [
            {
              "label": "Health",
              "value": "Medium",
              "detail": "keep the 10 / 10 / 10 baseline visible while proving the weekly export path and first-cycle training/mobility rhythm.",
              "tone": "watch"
            },
            {
              "label": "The People",
              "value": "Medium",
              "detail": "use the new relationship move template in a real family relationship block and trim it if it feels too heavy.",
              "tone": "watch"
            },
            {
              "label": "Home",
              "value": "Medium",
              "detail": "complete the next non-gym room reset without letting Facebook sale follow-up, yard momentum, or loose clutter reclaim the protected gym zone.",
              "tone": "watch"
            },
            {
              "label": "Wealth",
              "value": "Medium.",
              "detail": "review the regenerated Wealth dashboard after the 2026-07-03 recent service correction, then keep S corp cleanup and benefit application work separated in Linear.",
              "tone": "watch"
            },
            {
              "label": "VTC",
              "value": "Medium",
              "detail": "tighten follow-up cadence, stale-record handling, and review/referral loop while keeping VTC the active revenue driver.",
              "tone": "watch"
            },
            {
              "label": "Aligned Harmonics",
              "value": "Medium until migrated paths, skills, and validators are fully verified",
              "detail": "verify the new parent/sub-lane structure without activating support-business or creative expansion work.",
              "tone": "watch"
            }
          ]
        }
      ]
    },
    {
      "key": "system",
      "title": "System",
      "kicker": "Access / Generator",
      "summary": "The system page documents the route contract, source boundaries, noindex posture, and privacy checks.",
      "sections": [
        {
          "title": "Access Plan",
          "kicker": "Cloudflare",
          "tone": "green",
          "items": [
            {
              "label": "Gate 1",
              "value": "Cloudflare Access protects the dashboard route and nested dashboard paths before static content loads.",
              "detail": "",
              "tone": "green"
            },
            {
              "label": "Gate 2",
              "value": "The dashboard stays on the existing CJ Cinco Cloudflare Pages project.",
              "detail": "",
              "tone": "green"
            },
            {
              "label": "Gate 3",
              "value": "The route remains absent from the public homepage, nav, footer, robots file, and sitemap.",
              "detail": "",
              "tone": "green"
            },
            {
              "label": "Gate 4",
              "value": "The Next.js app does not implement a separate login system.",
              "detail": "",
              "tone": "green"
            }
          ]
        },
        {
          "title": "Source Contract",
          "kicker": "Exporter",
          "tone": "cyan",
          "items": [
            {
              "label": "Rule 1",
              "value": "Read only the bounded AOS generated dashboard snapshot, root command summaries, CJ Cinco lane summaries, and approved Wealth dashboard summary.",
              "detail": "",
              "tone": "cyan"
            },
            {
              "label": "Rule 2",
              "value": "Export AOS structure, goals, pressure, support gaps, coaching, queue counts, projection freshness, and summary metrics.",
              "detail": "",
              "tone": "cyan"
            },
            {
              "label": "Rule 3",
              "value": "Do not export raw communications, relationship records, local source paths, account details, credentials, private records, or raw evidence.",
              "detail": "",
              "tone": "cyan"
            },
            {
              "label": "Rule 4",
              "value": "Fail the build if deterministic leak checks find contact patterns, local paths, long account-like numbers, raw communication markers, or credential markers.",
              "detail": "",
              "tone": "cyan"
            }
          ]
        },
        {
          "title": "Privacy Checks",
          "kicker": "Build Gate",
          "tone": "green",
          "items": [
            {
              "label": "Check 1",
              "value": "No contact-pattern strings",
              "detail": "Deterministic final-output scan.",
              "tone": "green"
            },
            {
              "label": "Check 2",
              "value": "No local source paths",
              "detail": "Deterministic final-output scan.",
              "tone": "green"
            },
            {
              "label": "Check 3",
              "value": "No raw communication text",
              "detail": "Deterministic final-output scan.",
              "tone": "green"
            },
            {
              "label": "Check 4",
              "value": "No account-like identifiers",
              "detail": "Deterministic final-output scan.",
              "tone": "green"
            },
            {
              "label": "Check 5",
              "value": "No row-level private evidence",
              "detail": "Deterministic final-output scan.",
              "tone": "green"
            }
          ]
        }
      ]
    }
  ]
} as const;

export type DashboardData = typeof dashboardData;
